version: "3.3"
services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /pwndconfig:/config
    ports:
      - 20111:8080
    restart: unless-stopped