version: '3'
services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    ports:
      - "${PORT}:8081"

volumes:
  mongodb-data:
  mongodb-config: