services:
  mongodb:
    image: mongo:6.0
    container_name: umbrel-br-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.2-20
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME:-mongo}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    ports:
      - "8081:8081"

volumes:
  mongodb-data:
