version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-br-mongodb_web_1
      APP_PORT: 8081
    
  web:
    image: mongo-express:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: umbrel
      ME_CONFIG_MONGODB_ADMINPASSWORD: moneyprintergobrrr
      ME_CONFIG_BASICAUTH: "false"

  db:
    image: mongo:7
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: umbrel
      MONGO_INITDB_ROOT_PASSWORD: moneyprintergobrrr