version: '3'

services:
  app_proxy:
    image: "ghcr.io/umbrel/app-proxy:v1.0.0"
    environment:
      APP_HOST: ${APP_MONGODB_IP:-app}
      APP_PORT: 8081
      PROXY_AUTH_ADD: "false"

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ${APP_DATA_DIR}/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: umbrel

  app:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true